/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author Faris
 */
public class FrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrameAdmin
     */
    FrameLogin fl;
    DialogTambahProyek dtp;
    DialogTambahResource dtr;
    DialogTambahDokumentasi dtd;
    DialogTambahWaktu dtw;
    DialogTambahBiaya dtb;
    DialogEditProyek dep;
    DialogEditDokumentasi ded;
    DialogEditResource der;
    DialogEditWaktu dew;
    DialogEditBiaya deb;
    DialogHapusProyek dhp;
    DialogHapusDokumentasi dhd;
    DialogHapusResource dhr;
    DialogHapusWaktu dhw;
    DialogHapusBiaya dhb;
   
    
    public FrameAdmin() {
        initComponents();            
        setResizable(false);
        this.setEnabled(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Aplikasi CRUD");
        TambahProyek.addActionListener(new TambahProyek());
        TambahResource.addActionListener(new TambahResource());
        TambahDokumen.addActionListener(new TambahDokumen());
        TambahBiaya.addActionListener(new TambahBiaya());
        TambahWaktu.addActionListener(new TambahWaktu());
        EditProyek.addActionListener(new EditProyek());
        EditDokumen.addActionListener(new EditDokumen());
        EditResource.addActionListener(new EditResource());
        EditWaktu.addActionListener(new EditWaktu());
        EditBiaya.addActionListener(new EditBiaya());
        HapusProyek.addActionListener(new HapusProyek());
        HapusDokumen.addActionListener(new HapusDokumen());
        HapusResource.addActionListener(new HapusResource());
        HapusWaktu.addActionListener(new HapusWaktu());
        HapusBiaya.addActionListener(new HapusBiaya());
        Logout.addActionListener(new Logout());
        Exit.addActionListener(new Exit());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Dekstop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuProyek = new javax.swing.JMenu();
        TambahProyek = new javax.swing.JMenuItem();
        EditProyek = new javax.swing.JMenuItem();
        HapusProyek = new javax.swing.JMenuItem();
        MenuDokumentasi = new javax.swing.JMenu();
        TambahDokumen = new javax.swing.JMenuItem();
        EditDokumen = new javax.swing.JMenuItem();
        HapusDokumen = new javax.swing.JMenuItem();
        MenuResource = new javax.swing.JMenu();
        TambahResource = new javax.swing.JMenuItem();
        EditResource = new javax.swing.JMenuItem();
        HapusResource = new javax.swing.JMenuItem();
        MenuWaktu = new javax.swing.JMenu();
        TambahWaktu = new javax.swing.JMenuItem();
        EditWaktu = new javax.swing.JMenuItem();
        HapusWaktu = new javax.swing.JMenuItem();
        MenuBiaya = new javax.swing.JMenu();
        TambahBiaya = new javax.swing.JMenuItem();
        EditBiaya = new javax.swing.JMenuItem();
        HapusBiaya = new javax.swing.JMenuItem();
        MenuKeluar = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        Dekstop.setBackground(new java.awt.Color(255, 255, 255));
        Dekstop.setPreferredSize(new java.awt.Dimension(1366, 768));

        Dekstop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dekstop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DekstopLayout = new javax.swing.GroupLayout(Dekstop);
        Dekstop.setLayout(DekstopLayout);
        DekstopLayout.setHorizontalGroup(
            DekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DekstopLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addGap(874, 874, 874))
        );
        DekstopLayout.setVerticalGroup(
            DekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DekstopLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(181, 181, 181))
            .addGroup(DekstopLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 102));

        MenuProyek.setText("Manajemen Proyek");

        TambahProyek.setText("Tambah Proyek");
        MenuProyek.add(TambahProyek);

        EditProyek.setText("Edit Proyek");
        EditProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProyekActionPerformed(evt);
            }
        });
        MenuProyek.add(EditProyek);

        HapusProyek.setText("Hapus & Lihat Proyek");
        MenuProyek.add(HapusProyek);

        jMenuBar1.add(MenuProyek);

        MenuDokumentasi.setText("Manajemen Dokumentasi");

        TambahDokumen.setText("Tambah Dokumentasi");
        MenuDokumentasi.add(TambahDokumen);

        EditDokumen.setText("Edit Dokumen");
        EditDokumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDokumenActionPerformed(evt);
            }
        });
        MenuDokumentasi.add(EditDokumen);

        HapusDokumen.setText("Hapus & Lihat Dokumen");
        MenuDokumentasi.add(HapusDokumen);

        jMenuBar1.add(MenuDokumentasi);

        MenuResource.setText("Manajemen Alokasi Resource");

        TambahResource.setText("Tambah Alokasi Resource");
        MenuResource.add(TambahResource);

        EditResource.setText("Edit Alokasi Resource");
        MenuResource.add(EditResource);

        HapusResource.setText("Lihat & Hapus Alokasi Resource");
        MenuResource.add(HapusResource);

        jMenuBar1.add(MenuResource);

        MenuWaktu.setText("Manajemen Alokasi Waktu");

        TambahWaktu.setText("Tambah Alokasi Waktu");
        MenuWaktu.add(TambahWaktu);

        EditWaktu.setText("Edit Alokasi Waktu");
        MenuWaktu.add(EditWaktu);

        HapusWaktu.setText("Lihat dan Hapus Alokasi Waktu");
        HapusWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusWaktuActionPerformed(evt);
            }
        });
        MenuWaktu.add(HapusWaktu);

        jMenuBar1.add(MenuWaktu);

        MenuBiaya.setText("Manajemen Biaya");

        TambahBiaya.setText("Tambah Biaya Proyek");
        MenuBiaya.add(TambahBiaya);

        EditBiaya.setText("Edit Biaya Proyek");
        EditBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBiayaActionPerformed(evt);
            }
        });
        MenuBiaya.add(EditBiaya);

        HapusBiaya.setText("Hapus & Lihat Biaya Proyek");
        HapusBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBiayaActionPerformed(evt);
            }
        });
        MenuBiaya.add(HapusBiaya);

        jMenuBar1.add(MenuBiaya);

        MenuKeluar.setText("Keluar");

        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        MenuKeluar.add(Logout);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit.setText("Exit Program");
        MenuKeluar.add(Exit);

        jMenuBar1.add(MenuKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dekstop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dekstop, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void EditProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProyekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProyekActionPerformed

    private void EditBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBiayaActionPerformed

    private void HapusBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusBiayaActionPerformed

    private void EditDokumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDokumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditDokumenActionPerformed

    private void HapusWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusWaktuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new FrameAdmin().setVisible(true);
//            }
//        });
//    }

    private class TambahProyek implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){   
            dtp = new DialogTambahProyek(new FrameAdmin(), rootPaneCheckingEnabled);
            dtp.show();
        }        
    }
    private class EditProyek implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            dep = new DialogEditProyek(new FrameAdmin(), rootPaneCheckingEnabled);
            dep.show();
        }
    }
    private class HapusProyek implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            dhp = new DialogHapusProyek(new FrameAdmin(), rootPaneCheckingEnabled);
            dhp.show();
        }
    }
    
    private class TambahResource implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){   
            dtr = new DialogTambahResource(new FrameAdmin(), rootPaneCheckingEnabled);
            dtr.show();
        }        
    }
private class EditResource implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            der = new DialogEditResource(new FrameAdmin(), rootPaneCheckingEnabled);
            der.show();
        }
    }
private class HapusResource implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            dhr = new DialogHapusResource(new FrameAdmin(), rootPaneCheckingEnabled);
            dhr.show();
        }
    }
private class TambahDokumen implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){   
            dtd = new DialogTambahDokumentasi(new FrameAdmin(), rootPaneCheckingEnabled);
            dtd.show();
        }        
    }
private class EditDokumen implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            ded = new DialogEditDokumentasi(new FrameAdmin(), rootPaneCheckingEnabled);
            ded.show();
        }
    }
private class HapusDokumen implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            dhd = new DialogHapusDokumentasi(new FrameAdmin(), rootPaneCheckingEnabled);
            dhd.show();
        }
    }
private class TambahWaktu implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){   
            dtw = new DialogTambahWaktu(new FrameAdmin(), rootPaneCheckingEnabled);
            dtw.show();
        }        
    }
private class EditWaktu implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            dew = new DialogEditWaktu(new FrameAdmin(), rootPaneCheckingEnabled);
            dew.show();
        }
    }
private class HapusWaktu implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            dhw = new DialogHapusWaktu(new FrameAdmin(), rootPaneCheckingEnabled);
            dhw.show();
        }
    }
private class TambahBiaya implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){   
            dtb = new DialogTambahBiaya(new FrameAdmin(), rootPaneCheckingEnabled);
            dtb.show();
        }        
    }
private class EditBiaya implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            deb = new DialogEditBiaya(new FrameAdmin(), rootPaneCheckingEnabled);
            deb.show();
        }
    }
private class HapusBiaya implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            dhb = new DialogHapusBiaya(new FrameAdmin(), rootPaneCheckingEnabled);
            dhb.show();
        }
    }
    private class Logout implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            fl = new FrameLogin();
            fl.show();
            dispose();
        }
    }
    private class Exit implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae){
            dispose();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Dekstop;
    private javax.swing.JMenuItem EditBiaya;
    private javax.swing.JMenuItem EditDokumen;
    private javax.swing.JMenuItem EditProyek;
    private javax.swing.JMenuItem EditResource;
    private javax.swing.JMenuItem EditWaktu;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem HapusBiaya;
    private javax.swing.JMenuItem HapusDokumen;
    private javax.swing.JMenuItem HapusProyek;
    private javax.swing.JMenuItem HapusResource;
    private javax.swing.JMenuItem HapusWaktu;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenu MenuBiaya;
    private javax.swing.JMenu MenuDokumentasi;
    private javax.swing.JMenu MenuKeluar;
    private javax.swing.JMenu MenuProyek;
    private javax.swing.JMenu MenuResource;
    private javax.swing.JMenu MenuWaktu;
    private javax.swing.JMenuItem TambahBiaya;
    private javax.swing.JMenuItem TambahDokumen;
    private javax.swing.JMenuItem TambahProyek;
    private javax.swing.JMenuItem TambahResource;
    private javax.swing.JMenuItem TambahWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
